### ISSUE TITLE
Lỗi form thu tự do.

### ISSUE THREAD

**Issue by lqbinh1987** [oth-dhghospital/dhg.hospitalfees#11]
Fees Vào menu Phiếu thu\Thu tự do thì báo lỗi như hình: Npgsql.NpgsqlException:
each UNION query must have the same number of columns
Data: binh_dblapvo_thu_tu_do
![image](https://user-images.githubusercontent.com/99630883/162880324-3880e916-fb27-4eb9-9b14-e12b1a76f7b8.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
[Cập nhật tại đây](https://github.com/oth-dhghospital/dhg.hospitalfees/commit/a04f619e773dbde0547d3c8f41393f1da41d9d57)
