### ISSUE TITLE
Lỗi xóa phiếu thu đã lập phiếu thu tổng hợp.

### ISSUE THREAD

**Issue by lqbinh1987** [oth-dhghospital/dhg.hospitalfees#13]
Những phiếu thu đã được lập phiếu thu tổng theo BN nhưng vẫn xóa được.
Data: test_042022.
![image](https://user-images.githubusercontent.com/99630883/163529782-370ecf83-25fd-4127-8d71-31ab1a614c28.png)
![image](https://user-images.githubusercontent.com/99630883/163529800-6b4778d1-2f4b-4644-9321-32d40c4a19cd.png)
![image](https://user-images.githubusercontent.com/99630883/163529826-5237c0d7-169a-4de8-a0c5-0a4e8d013d38.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cập nhật tại đây 68f4a96c198e18c3dc9fe01f1441b3390c400126
