### ISSUE TITLE
Mẫu Phiếu Thu tự thiết kế - chi tiết CLS, tổng tiền thuốc

### ISSUE THREAD

**Issue by BlueTea92** [oth-dhghospital/dhg.hospitalfees#16]
- PHÒNG KHÁM BÁC SĨ BẮC - QUẢNG NGÃI
- Sử dụng tham số : hosfees.phieuthutuin
- Nhờ hỗ trợ mẫu Phiếu thu tự thiết kế thể hiện chi tiết từng CLS nhưng tiền thuốc gom chung 1 dòng

![image](https://user-images.githubusercontent.com/97272332/165041207-0e01c22d-ea9c-45d3-9f8a-fde268028dfd.png)
![image](https://user-images.githubusercontent.com/97272332/165041454-a12692a7-cbfc-4beb-88e5-16ca0ee6814e.png)
![image](https://user-images.githubusercontent.com/97272332/165040795-06df7f0a-9c3c-4b13-a387-12fe4b6c5f3f.png)
- Mẫu hiện tại đang thể hiện chi tiết CLS và thuốc

- Data máy chủ: tra_pkbsbac_fees
- Data: https://drive.google.com/file/d/1_0D5v77WOdgVJgzdjccEIv5rhmoEBG39/view?usp=sharing

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cập nhật tại đây: c7cf6ba0032be44ecdd2b335a3af50cf35c5aecf
Đề nghị thiết kế lại trang in cho khách hàng ở một số điểm như sau:
- STT: Canh giữa
- Đơn giá, Số lượng, Thành tiền: Canh Phải, và có phân cách phần ngàn trên số tiền

**Comment by BlueTea92** [comment]
![image](https://user-images.githubusercontent.com/97272332/168204339-ab115917-d6d7-4ee7-a066-019739dc281f.png)
![image](https://user-images.githubusercontent.com/97272332/168204394-ccfa09b0-528b-4186-9e84-e6b48755610c.png)

em chỉnh lại phiếu thu rồi nhưng chưa tìm được para nào phù hợp với yêu cầu
có para mới hay cần cấu hình gì thêm không vậy anh?
