### ISSUE TITLE
Phiếu thu không nhận được kết quả trả về từ  HDDT của VAT

### ISSUE THREAD

**Issue by lqbinh1987** [oth-dhghospital/dhg.hospitalfees#17]
Phiếu thu đã lập HDDT thành công nhưng lại báo lỗi và không nhận được kết quả trả về, phải đồng bộ lại 2-3 lần thì mới nhận kết quả trả về.
Data: dbnhidong_032022.

![image](https://user-images.githubusercontent.com/99630883/165420880-2bba9081-3b65-4dfd-9fe8-6a09ffa7d0e8.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cập nhật tại đây 23f1ef44ca158c183025ecff178f652ec2efa4da
