### ISSUE TITLE
Hóa đơn thu tiền nhà thuốc không lấy được mã số thuế

### ISSUE THREAD

**Issue by o-ngtrieuhau861gmailcom** [oth-dhghospital/dhg.hospitalfees#22]
[**DH_HopTuan_20220509.pdf**](https://github.com/oth-dhghospital/dhg.hospitalfees/files/8657412/DH_HopTuan_20220509.pdf)
Hóa đơn thu tiền nhà thuốc không lấy được mã số thuế đối với bệnh nhân có nhập mã số thuế tại hóa đơn viện phí.

Chưa có dữ liệu kiểm tra nhé @le-an-87

**Comment by le-an-87** [comment]
Trường hợp này khi nhận bệnh không có nhập mã số thuế và địa chỉ công tác của bệnh nhân
nhưng có lập hóa đợ viện phí và nhập mã số thuế và địa chỉ công tác
khi qua lập hóa đơn nhà thuốc thì Fees không load được mã số thuế đã nhập bên hóa đơn viện phí
tên data: an_dalieu_masothue

hóa đơn viện phí
![image](https://user-images.githubusercontent.com/96155021/168240404-3c053353-a8bf-4cdf-8816-971a96ae5d3a.png)

Khi lập hóa đơn nhà thuốc
![image](https://user-images.githubusercontent.com/96155021/168240561-bc143ed5-522d-4cca-a352-7965f8963d9c.png)

thông tin nhận bệnh
![image](https://user-images.githubusercontent.com/96155021/168240632-b2f572f1-98cd-422a-87ee-664390f22d27.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cập nhật tại đây 44a12f0b07ca7a3f63b18d3c6345fef5a574ca3d

**Comment by le-an-87** [comment]
chổ mã số thuế phiếu thu nhà thuốc lấy được thông tin rồi đó anh ơi
