### ISSUE TITLE
Cập nhật TT78-VNPT(nhà thuốc).

### ISSUE THREAD

**Issue by lqbinh1987** [oth-dhghospital/dhg.hospitalfees#23]
Theo tài liệu kỹ thuật bên VNPT thì thay đổi thẻ "Amount" thành thẻ "Total" trong Product.
Bửa hổm dối với viện phí thì đã ok, nhưng nhà thuốc thì chưa đổi được sang thẻ Total, nhà thuốc đang cấu hình truyền chi tiết từng mặt hàng.
Data: bvmat.
BN: Dương Văn Công - 2204000003, ngày 01/04

![image](https://user-images.githubusercontent.com/99630883/167574932-657d6470-bd6b-4658-8b1b-caa9308d55ac.png)
![image](https://user-images.githubusercontent.com/99630883/167575022-7cae82f9-d607-4519-a3f2-ac308efaca4c.png)
![image](https://user-images.githubusercontent.com/99630883/167582109-aca209b8-753a-4a0d-8059-b9061a4c1617.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Đề nghị chuyển qua module Printer và test bản cập nhật mới nhất xem còn bị tình trạng này hông nhé
