### ISSUE TITLE
FEES load chứng từ thu phí bệnh nội trú báo lỗi

### ISSUE THREAD

**Issue by le-an-87** [oth-dhghospital/dhg.hospitalfees#24]
Fees phiên bản 27/4/2022 khi load chứng từ thu phí nội trú báo lỗi
tên data: an_tamnong_treatfees
![image](https://user-images.githubusercontent.com/96155021/167756576-749eb725-b580-4118-9237-740f75fd098b.png)
file lỗi
[loi_Fees_tamnong.txt](https://github.com/oth-dhghospital/dhg.hospitalfees/files/8666231/loi_Fees_tamnong.txt)

**Comment by o-ngtrieuhau861gmailcom** [comment]
PostgresSQL máy chủ bị lỗi oid rồi, nên phát sinh lỗi này, kiểm lại lỗi này bằng cách cài PostgreSQL tại máy cục bộ sẽ hông bị.
