### ISSUE TITLE
Cập nhật TT78 cho  HDDT của MISA.

### ISSUE THREAD

**Issue by lqbinh1987** [oth-dhghospital/dhg.hospitalfees#25]
Theo tài liệu của MISA thì có thay đổi về cách kết nối API(chi tiết có file tài liệu kèm theo) và bổ sung thêm một số trường sau:
Body: bổ sung thêm các field: Ghi chú ý nghĩa các trường thì xem ở tài liệu chi tiết theo link https://doc.meinvoice.vn/api/Document/InvoiceInfo.html.
Data: binh_tamhan_dtp
- InvSeries
- InvoiceName
- InvDate
- BuyerCode
- ReferenceType
- OrgInvoiceType
- OrgInvTemplateNo
- OrgInvSeries
- OrgInvNo
- OrgInvDate
- TotalSaleAmountOC
- TotalSaleAmount
- TotalAmountWithoutVATOC
- TotalVATAmountOC
- TotalDiscountAmountOC
- TotalAmountOC
- TotalAmount
- TotalDiscountAmount
- TotalAmountInWords
- ItemType
- SortOrder
- AmountOC
- AmountWithoutVATOC
- DiscountAmountOC
- AmountWithoutVAT
- VATRateName
- "TaxRateInfo": [
                          {
                            "VATRateName": "5%",
                            "AmountWithoutVATOC": 950000.0,
                            "VATAmountOC": 47500.0
                          }
                       ]
[Su khac nhau giua API moi va API cu.docx](https://github.com/oth-dhghospital/dhg.hospitalfees/files/8683910/Su.khac.nhau.giua.API.moi.va.API.cu.docx)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Hiện tại đang sử dụng dll của bên MISA để thực hiện, mà trong tài liệu này hông thấy đề cập, nên phải đợi liên hệ bên MISA hỗ trợ tiếp mới được nhé.

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cập nhật tại đây https://github.com/oth-dhghospital/dhg.hospitalfees/commit/19c4c505263b87c2c4899ffaf6877e51129915c8
- Bổ sung cấu hình theo cấu trúc mới của MISA
![image](https://user-images.githubusercontent.com/58720300/172559444-4a106371-20a0-471d-8d87-0fbcb763bb1c.png)
