### ISSUE TITLE
Thay đổi trường tuổi - HDDT TT78 VNPT

### ISSUE THREAD

**Issue by lqbinh1987** [oth-dhghospital/dhg.hospitalfees#26]
Chuyển sang TT78 thì HDDT của VNPT không còn xài thẻ **KindOfService** nữa, đổi sang thẻ **extra6**.
Data: binh_tamnong, phiếu thu nội trú ngày 10/5.
Đã cấu hình cổng demo

![image](https://user-images.githubusercontent.com/99630883/168248193-b79986b7-7c70-40fd-a284-cbd5e6593352.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Xin lại tài liệu full để xem cái thẻ đó như thế nào nhé @lqbinh1987

**Comment by o-ngtrieuhau861gmailcom** [comment]
- Cập nhật tại đây 9c5ce48bc7f5ce4b94114917823127ba8ece773e
- KindOfService nữa, đổi sang thẻ Extra6 sẽ có tác dụng khi đổi cấu hình Amout => Total (áp dụng TT78)
