### ISSUE TITLE
In lại phiếu tạm ứng, hoàn ứng

### ISSUE THREAD

**Issue by o-ngtrieuhau861gmailcom** [oth-dhghospital/dhg.hospitalfees#27]
Bệnh viện Nhi Đồng Cần Thơ yêu cầu không cho phép in lại phiếu tạm ứng và hoàn ứng nếu đã in rồi. Và những tài khoản được phép in lại mới được phép in lại.

**Comment by o-ngtrieuhau861gmailcom** [comment]
![image](https://user-images.githubusercontent.com/58720300/168455578-a0b408b9-4389-4863-a374-0c88aff132b1.png)

**Comment by nghibi** [comment]
Bình check lại coi ok chưa nha.

**Comment by lqbinh1987** [comment]
ok rồi anh, còn phần in lại hddt thì sao anh Bi? chờ cái issue này lun hay e làm issue khác?

**Comment by nghibi** [comment]
Close cái này đi, anh nói Quốc yêu cầu gì nó ghi cụ thể biên bản đi rồi tính.

**Comment by lqbinh1987** [comment]
Vậy nhờ a Hậu close nhe.
