### ISSUE TITLE
Lập HDDT-VAT không được.

### ISSUE THREAD

**Issue by lqbinh1987** [oth-dhghospital/dhg.hospitalfees#29]
Bấm vô nút **Lập và in hóa đơn điện tử** không có tác dụng, bấm vô **nút Lập hóa đơn điện tử** thì ok.
Data: binh_nhidong, phiếu thu ngoại trú ngày 26/04.
![image](https://user-images.githubusercontent.com/99630883/169791103-ddb42a4a-2470-4372-aaaa-44278a9ccd56.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cái này lỗi ở cổng VAT, bên đó nói đã ok rồi, nhờ @lqbinh1987  test lại nhé

**Comment by lqbinh1987** [comment]
Em test lại thì lập HDDT đc rồi, nhưng nút **Lập và in hóa đơn điện tử** bị như lúc trước, bấm vô 2 lần mới được, bấm lần đầu là trên cổng có số nhưng phần mềm chưa lấy được số hddt, bấm lần 2 mơi có.
![image](https://user-images.githubusercontent.com/99630883/170176080-ebe7792f-fc9d-4f49-a372-236b8e11ad83.png)
