### ISSUE TITLE
Hóa đơn điện tử nhà thuốc không tính được tiền thuế  -BV Tim Mạch AG

### ISSUE THREAD

**Issue by lqbinh1987** [oth-dhghospital/dhg.hospitalfees#3]
- Khi lập hóa đơn điện tử cho phiếu thu tổng của nhà thuốc chưa tính được tiền thuế giống như lập hóa đơn cho từng phiếu thu.
- Phiếu thu tổng đã lập hóa đơn điện tử nhưng trên form không hiển thị thông tin của hóa đơn điện tử(số mẫu, ký hiệu, số hóa đơn).
- Dữ liệu trên server: dbtimmach_022022, hóa đơn tổng ngày 08/02, số chứng từ của phiếu thu tổng BLT22.0001/02
_Ghi chú: đã cấu hình nhà thuốc qua cổng demo._

![image](https://user-images.githubusercontent.com/99630883/159862451-f6b8e1e3-f7aa-47b7-a3f3-97031796c1ea.png)
![image](https://user-images.githubusercontent.com/99630883/159863627-7514bf78-24af-4b2f-b1da-a0e467a00f03.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
> * Phiếu thu tổng đã lập hóa đơn điện tử nhưng trên form không hiển thị thông tin của hóa đơn điện tử(số mẫu, ký hiệu, số hóa đơn).
=> Xác nhận lỗi, sẽ chỉnh lại trong bản cập nhật mới 

> * Khi lập hóa đơn điện tử cho phiếu thu tổng của nhà thuốc chưa tính được tiền thuế giống như lập hóa đơn cho từng phiếu thu.
 => Với cấu hình hiện tại sẽ không tính được phần trăm thuế, vì %thuế đang cho phép cấu hình theo lý do thu, nó dính tới lấy % của thuốc, và đây là phiếu thu tổng, nên những phần chi tiết này sẽ không lấy được. **Đề xuất phương án để áp dụng trường hợp này là Thêm tham option mới đối với những phiếu thu tổng, sẽ áp dụng %thuế theo giá trị Thuế suất mà người dùng lập khi thêm phiếu thu. Xem xét như vậy có áp dụng được đối với bệnh viện hông, thì xác nhận thực hiện**

**Comment by lqbinh1987** [comment]
% thuế để e xác nhận với Bv

Vào Th 5, 7 thg 4, 2022 lúc 10:48 Ông Triệu Hậu ***@***.***>
đã viết:

**Comment by lqbinh1987** [comment]
> * Đề xuất phương án để áp dụng trường hợp này là Thêm tham option mới đối với những phiếu thu tổng, sẽ áp dụng

Em dã trao đổi với BV, thống nhất như phương án anh đề ra nhe anh Hậu.

**Comment by o-ngtrieuhau861gmailcom** [comment]
[Cập nhật tại đây](https://github.com/oth-dhghospital/dhg.hospitalfees/commit/a04f619e773dbde0547d3c8f41393f1da41d9d57)
