### ISSUE TITLE
Lỗi báo cáo có sử dụng biên lai

### ISSUE THREAD

**Issue by lqbinh1987** [oth-dhghospital/dhg.hospitalfees#31]
1. Báo cáo sử dụng biên lai bị lỗi khi chuyển sang TT78, do BV sử dụng cấu hình cập nhật lại số biên lai, quyển, ký hiệu trên phần mềm khi lập HDDT thành công, vì lúc này số hóa đơn điện tử trả về có chuỗi ký tự trong đó, ví dụ như: C22TVP1...C22TVP2..C22TVP3...C22TVP4...(Hình 1 và 2)
2. Trong báo cáo bảng kê biên lai thu nó tự chia ra nhiều quyển.(Hình 3)
3. Trong form Hóa đơn điện tử\ lập hóa đơn tổng cả bệnh viện, lỗi khi Lập phiếu thu tổng, vì trước đó đã lập được 1 hddt(giá trị trả về theo dạng của TT78) và cập nhật số hddt về cho thuchi.sobl là 22TNT91, có chuỗi ký tự nên bị lỗi, e thử chỉnh thuchi.sobl thành số thì lập tiếp phiếu thu tổng được.(Hình 4, 5)

Data: binh_timmach_ag_062022.

Hình1
![image](https://user-images.githubusercontent.com/99630883/171438659-5141dc58-2400-4d68-9f47-8c74def365c2.png)

Hình 2
![image](https://user-images.githubusercontent.com/99630883/171438618-8e1a8909-f942-480c-97cd-b6f1bb870657.png)

Hình 3
![image](https://user-images.githubusercontent.com/99630883/171778090-25ae9e0c-c775-4601-bda3-744a03ae9ecf.png)

Hình 4
![image](https://user-images.githubusercontent.com/99630883/171778107-c14d7fdc-6c7c-49d3-b7b7-4c8200bbf75f.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cập nhật tại đây https://github.com/oth-dhghospital/dhg.hospitalfees/commit/a6ccb77b797e4769644ada4b5624e4428630f1b0
