### ISSUE TITLE
Lỗi số biên lai có thể nhập dư số 0 phía trước

### ISSUE THREAD

**Issue by BlueTea92** [oth-dhghospital/dhg.hospitalfees#33]
BV TMH báo lỗi số biên lai bị dư số 0 so với số biên lai trong quyển biên lai
- Khi nhập thêm số 0 vào trước số biên lai thì phần mềm không kiểm tra được số ký tự của số biên lai so với số ký tự trong danh mục quyển biên lai
- Khi thao tác sai hoặc nhập lại số biên lai đã xóa có thể bị lỗi này
![ảnh](https://user-images.githubusercontent.com/97272332/171785248-27ee11f1-fa74-4297-98e8-917adcb582b6.png)
![ảnh](https://user-images.githubusercontent.com/97272332/171785259-d53a47ad-490f-478b-a9e1-65c0562a7032.png)

- Data test: tra_tmh_fees
- Ngày 3/6/2022 thu phí ngoại trú

**Comment by o-ngtrieuhau861gmailcom** [comment]
Bổ sung cảnh báo khi độ dài lớn hơn 7 tại đây https://github.com/oth-dhghospital/dhg.hospitalfees/commit/946174349be1904eabc87c7eac5d1a993d6b4981
