### ISSUE TITLE
Bổ sung 1 số trường trong XML của HDDT VNPT.

### ISSUE THREAD

**Issue by lqbinh1987** [oth-dhghospital/dhg.hospitalfees#36]
Như bên kỹ thuật của VNPT, xml bổ sung các thông tin này để dữ liệu sang thuế đúng theo yêu cầu:
<GrossValue>Thành tiền không chịu thuế (NUMBER(18,0))</GrossValue>
<VatAmount0>Tiền thuế 0% (NUMBER(18,0))</VatAmount0>
<GrossValue0>Thành tiền trước thuế 0% (NUMBER(18,0))</GrossValue0>
<VatAmount5>Tiền thuế 5% (NUMBER(18,0))</VatAmount5>
<GrossValue5>Thành tiền trước thuế 5% (NUMBER(18,0))</GrossValue5>
<VatAmount8>Tiền thuế 8% (NUMBER(18,0))</VatAmount8>
<GrossValue8>Thành tiền trước thuế 8% (NUMBER(18,0))</GrossValue8>
<VatAmount10>Tiền thuế 10% (NUMBER(18,0))</VatAmount10>
<GrossValue10>Thành tiền trước thuế 10% (NUMBER(18,0))</GrossValue10>.

Ví dụ: 
Nếu Không chịu thuế thì đưa tổng tiền vào <GrossValue>
Nếu 0% thì đưa tiền thuế vào <VatAmount0> và tổng tiền trước thuế vào <GrossValue0>.
Nếu 5% thì đưa tiền thuế vào <VatAmount5> và tổng tiền trước thuế vào <GrossValue5>.
Nếu 0% thì đưa tiền thuế vào <VatAmount8> và tổng tiền trước thuế vào <GrossValue8>.
Nếu 0% thì đưa tiền thuế vào <VatAmount10> và tổng tiền trước thuế vào <GrossValue0>.

File xml mẫu có 10%VAT
[Invoices_VAT10.docx](https://github.com/oth-dhghospital/dhg.hospitalfees/files/8868388/Invoices_VAT10.docx)

Data: bvmat_t5.

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cập nhật tại đây https://github.com/oth-dhghospital/dhg.hospitalfees/commit/cb02c0d5bad582c7191b1cf7f8ec541cb3417555

**Comment by lqbinh1987** [comment]
> Như bên kỹ thuật của VNPT, xml bổ sung các thông tin này để dữ liệu sang thuế đúng theo yêu cầu: Thành tiền không chịu thuế (NUMBER(18,0)) Tiền thuế 0% (NUMBER(18,0)) Thành tiền trước thuế 0% (NUMBER(18,0)) Tiền thuế 5% (NUMBER(18,0)) Thành tiền trước thuế 5% (NUMBER(18,0)) Tiền thuế 8% (NUMBER(18,0)) Thành tiền trước thuế 8% (NUMBER(18,0)) Tiền thuế 10% (NUMBER(18,0)) Thành tiền trước thuế 10% (NUMBER(18,0)).
> 
> Ví dụ: Nếu Không chịu thuế thì đưa tổng tiền vào Nếu 0% thì đưa tiền thuế vào và tổng tiền trước thuế vào . Nếu 5% thì đưa tiền thuế vào và tổng tiền trước thuế vào . Nếu 0% thì đưa tiền thuế vào và tổng tiền trước thuế vào . Nếu 0% thì đưa tiền thuế vào và tổng tiền trước thuế vào .
> 
> File xml mẫu có 10%VAT [Invoices_VAT10.docx](https://github.com/oth-dhghospital/dhg.hospitalfees/files/8868388/Invoices_VAT10.docx)
> 
> Data: bvmat_t5.
