### ISSUE TITLE
Bổ sung lý do xóa hóa HDDT VIETTEL.

### ISSUE THREAD

**Issue by lqbinh1987** [oth-dhghospital/dhg.hospitalfees#37]
Hiện tại khi phần mềm mính xóa HDDT thì có truyền vào "additionalReferenceDesc" mặc định là "hủy hóa đơn", giờ Thuế yêu cầu khi xóa Hóa đơn phải có lý do cụ thể chứ không được mặc định chổ này.
Đề nghị hiện bảng cho nhập lý do xóa khi bấm nút **Xóa hóa đơn** hoặc nút **Xóa** phiếu thu(đã lập hddt), và truyền lý do đó vào trường "additionalReferenceDesc" của cổng HDDT.

Data: dblaivung2020027123_2204003687_n2022001068.
Mã BANT có phiếu thu: N2022001068
![image](https://user-images.githubusercontent.com/99630883/172974037-eea57cc5-19b5-4cc5-94f4-b767c57eed6c.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cập nhật tại đây https://github.com/oth-dhghospital/dhg.hospitalfees/commit/bbe3708f844ae1f97c60f093b7fa8c63e601d9c8
![image](https://user-images.githubusercontent.com/58720300/173722965-0c49fa83-696c-4056-aa4e-1dc2d9229479.png)
![image](https://user-images.githubusercontent.com/58720300/173722982-a4159d8a-f664-49f3-9703-d4432ce2a875.png)
![image](https://user-images.githubusercontent.com/58720300/173723109-d984d4e3-d891-4bdd-bcde-5d33021b4897.png)
