### ISSUE TITLE
Cập nhật thêm HDDT MISA.

### ISSUE THREAD

**Issue by lqbinh1987** [oth-dhghospital/dhg.hospitalfees#39]
1. Hiện tại phần mềm truyền tên BN vào cả 2 trường "BuyerLegalName" và "BuyerFullName", giờ MISA yêu cầu tách ra dùm, truyền tên công ty vào "BuyerLegalName", còn tên BN vào "BuyerDisplayName".
2. Phần địa chỉ, nếu có địa chỉ công ty hoặc của BN thì truyền vào **"BuyerAddress"**, không truyền vào "SellerAddressLine" như hiện tại nữa.
Data test: binh_tamthandtp_

**Comment by o-ngtrieuhau861gmailcom** [comment]
- Cập nhật tại đây https://github.com/oth-dhghospital/dhg.hospitalfees/commit/7f953c0ae844bec125bf2f9ae86e11cd8b5fc136
