### ISSUE TITLE
Lỗi BC Bảng kê nợ viện phí và theo dõi chi phí bệnh nhân nội trú

### ISSUE THREAD

**Issue by le-an-87** [oth-dhghospital/dhg.hospitalfees#5]
Phần thu tiền nội trú không có phát sinh nợ
![image](https://user-images.githubusercontent.com/96155021/160988312-b0a4a43e-8ce8-4dd5-82f0-f476b09235b2.png)
Nhưng Bảng kê nợ viện phí và theo dõi chi phí bệnh nhân nội trú lại hiển thị bệnh nhân nợ tiền viện phí!
![image](https://user-images.githubusercontent.com/96155021/160988459-846af597-5517-478a-8792-0f206ba8cf5d.png)
![image](https://user-images.githubusercontent.com/96155021/160988493-7d21219b-abd5-4263-8180-ca6d8769b58a.png)
Dữ liệu bv lấp vò
https://drive.google.com/file/d/1SaojSh63Vdi9TCjpvSexEJ9kKStFpRMG/view?usp=sharing

**Comment by o-ngtrieuhau861gmailcom** [comment]
Fix tại : https://github.com/oth-dhghospital/dhg.hospitalfees/commit/30de6067a8bf1b89d9d1d626bacf3518b705fd86
