### ISSUE TITLE
A Hậu khỏi kiểm(đã xong) - Lỗi số biên lai chưa sử dụng.

### ISSUE THREAD

**Issue by lqbinh1987** [oth-dhghospital/dhg.hospitalfees#7]
Khi lập xong phiếu thu, sau đó lập tiếp thì số biên lai chưa thu tự động nhảy nhưng lại báo đã sử dụng rồi, phải nhấn chọn quyển lại(vẫn nhảy số chưa thu) mới thu được.
Data: dbgovap, ngày 22/03

![image](https://user-images.githubusercontent.com/99630883/161513182-a859a361-338a-4c1f-8126-79dfedd8dd3c.png)
![image](https://user-images.githubusercontent.com/99630883/161513228-be29159b-d552-4bde-9d4e-cbb576a90eb4.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cái nào xong thì nhớ vào đây check để close lại nhé, khỏi theo dõi nữa nhé.
![image](https://user-images.githubusercontent.com/58720300/162129934-a8dbaf71-9fb7-4f97-86a1-61db4802f2a6.png)

**Comment by lqbinh1987** [comment]
Ok anh.

Vào Th 5, 7 thg 4, 2022 lúc 12:55 Ông Triệu Hậu ***@***.***>
đã viết:
