### ISSUE TITLE
Lỗi PK Đồng Tây - Bảng kê BANT theo dõi chi phí điều trị

### ISSUE THREAD

**Issue by le-an-87** [oth-dhghospital/dhg.hospitalfees#8]
PK đông tây
Tổng tiền phiếu thu 492,907 nhưng BC theo dõi bảng kê chi phí BANT hiển thị 438,100
dữ liệu: dbdongtay2022
![image](https://user-images.githubusercontent.com/96155021/161913904-c23d5708-06f1-43ea-ad05-cd7ad376b016.png)
![image](https://user-images.githubusercontent.com/96155021/161914042-adb700ea-0da0-4e81-8b4c-a42ecb00cd18.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Fix tại : https://github.com/oth-dhghospital/dhg.hospitalfees/commit/30de6067a8bf1b89d9d1d626bacf3518b705fd86
