### ISSUE TITLE
Phiêu thu tổng không hiển thị thông tin của HDDT.

### ISSUE THREAD

**Issue by lqbinh1987** [oth-dhghospital/dhg.hospitalfees#9]
Phiếu thu tổng đã lập hddt, vẫn hiển thông tin của hddt của phiêu thu đó, nhưng click sang phiêu thu khác, thì không load được dl hddt của phiếu thu khác. -> không load được dữ liệu hddt lên form khi click chuột vô phiếu thu.
Data: dbtimmach_022022
![image](https://user-images.githubusercontent.com/99630883/161931040-4b330b7f-8427-471c-883b-9b349d038e34.png)
![image](https://user-images.githubusercontent.com/99630883/161931100-d08b844b-197a-4735-a6f4-b183e9f57228.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Fix tại : https://github.com/oth-dhghospital/dhg.hospitalfees/commit/30de6067a8bf1b89d9d1d626bacf3518b705fd86
